# Beginning

## He and she

You write a lot, he said. 

By that time, he didn’t know what had happened with him along all those years. He didn’t know the places where he had been, lost; the languages he had forgotten, and those he hadn’t learnt; the women that kept his hopes, and those he hadn’t loved; the friends he hadn’t visit, and therefore had disappeared; the wasted time scrolling people up and down…

As it is supposed, it started with isolation. The uncomfortable feeling of being alone. Nevertheless, in some sense, he had created those situations. The suffering needed for evolving was his most intimate creation. Full of pain, full of hopes. Depending on the audience, depending on the artist, depending on the piece of art, depending on the critics, depending on the art itself. It was what it was. The present moment transformed in the uneasiness of a foreigner who, willingly, missed his home, if there was any. 

Then he stopped. At that moment, he sipped the tea. Slowly, calmly, savoring the presence of the room, breathing the essence of life. Why did their thoughts have to invade these moments? Why couldn’t the peace last forever? It had happened again.

He turned on the laptop searching for answers. The machine stole his life during the initialization. Impatiently, he looked a bug flying among the lost seconds of his desk. The speed of technology would never be enough for the unsatisfied human brain. Without any particular reason, looking to that bug he remembered that day. The day he met her.

She was just doing it for love. Sometimes she liked to stare at people who were waiting. What do people do when they do not have anything else to do? The expressive faces and grimaces reflecting their inner fights; the self-grooming behaviors as attempts in search of lost time. She used to encounter the most creative people while scrutinizing their spare time. It seemed to her that repressed artist disclosure their best works without being aware. Interestingly, creations that appear conscientiously usually end unpublished. As it was her case. As it was his case. 

She could have written more. However, she used paper in a personal way. The silky blankness of new sheets was her favorite way of procrastination. Streams of thoughts were missing in exchange for the pleasurable feeling of observing her fingers sliding smoothly over the satin cellulose.

Anyhow, she loved those waiters. That is how she liked to call them. She also loved curious words. Why the waiters are called waiters when are the clients those who complain about being waiting? Waiting for the waiters... It may not have sense, but she always lost her attention with these kinds of thoughts.  

Thinking about attention, he remembered he was waiting for the laptop to light up, a task that had been completed several minutes ago. Where was now the unbeatable human brain? He typed the password and wait again while the screen was loading. Now, it was the blackness of the screen what led him to the subsequent thoughts.

He recalled her complaining about how people had stopped waiting. Her loved waiters had become watchers. They had stopped creating to gaze uninterruptedly at a black mirror. People were sinking in their own reflection. The unavoidable narcissism that, as was later demonstrated and against all the forecasting, would lead humankind to its vital awakening. Regardless of the height of the fall, the brain knows how to finish the nightmare just moments before crashing against the concrete. 

She became mad at it, and for boosting her mood, she usually went to hostels to see strangers sleep. That was her second hobby. That way, she managed to avoid the guilty feelings experienced when gawking hard-workers. By listening to the moans and wails of the room she could guess if someone would have to change their underpants the next morning. She had become an expert in inner conversations. After hundreds of unexpected encounters in the dark, and through conscientious and delicate practice, she was able then to maintain profound dialogues with somnambulist and sleep talkers. Again, words. Sometimes arbitrary, sometimes not. Whatever the case, she decided what to do with her time. Time is a personal decision. Waiting is just an option. Sleep is another.

He recovered his mind and looked at the screen, now colorful and full of possibilities. Maybe, too many possibilities.

Through his pupils, the LCD was draining his brain. The basic question remained in his head, what was he looking for? Was it himself? Was how to maintain endurable and fruitful relationships? Was how to kill the tiny flies attracted by the over-matured fruit that accumulated in his room?  Were techniques to not to lose his attention? Whatever it was, his fingers opened Facebook. He saw his profile photo, he saw his friends’ pictures, he saw the video of a guy killing flies with an electrified racquet. If it weren’t because he had already forgotten about what he was looking for, Facebook could have become the most effective tool.

Another hour was gone, fortunately, this time without pain, this time without feeling. After bombing his mind with stimulation, his memory just retained the video of the dying flies and that photo, taken five long years ago. He wrote down in the To Buy List “Electrified racquet”. He took the coat, opened the door and went to the street. He would take the bike; the last experience with public transport could not be considered as very encouraging. 

That photo had become another burden on his heart. He had not decided to see it. As it had faded away, it had just appeared on the screen. Regrettably, it remained in his mind. He had neither possibilities nor freedom of election. He was imposed to watch what other people want him to watch. The printed copy of the picture awaited in his shoebox, hidden for five years now. 

## Lies and truths

Luckily, he passed over the kitchen when closing the door. Simply that. Over time, with doses of patience and self-acceptance, the assemblage of mugs, spoons and tea bags arrayed on the desk ends up provoking feelings of melancholia instead of flagellation. Every object has its own story. Giving it a thought, it is almost impossible to disorder a room in purpose. Outside, on the street, the once polished and spotless white bike had become a bunch of soldered iron stick and gears with a color closer to dirty orange than to clean brown. It was not that he had not had free time, but one never finds the right moment to do what one has to do. 

He mounted on and pedaled. The grubby sound that accumulated rust created was not as penetrating as the previous month. It is matter of getting use to things. Who is to guilt? One day a pimple appears on your check, you pop it, a week with a scab. A week with a scab. Easier to read than to bear it. Anyhow, weeks finish, and the reflection in the mirror depends on how many other pimples had appeared that week. Maybe it is just lack of self-discipline. 

He became so superficial when riding the bike. The sticky and deep thought of how the rust; like the cortisol or the mold; accumulates gradually and steadily on the inner mechanism of life were too introspective ideas for driving. He did not want to run over any innocent being. He was a fiery protector of defenseless grandmas that are unfairly sent to the hospital. Quixote would have understood him. 

The neighing of his Rocinante were getting louder and louder. Helped by his feet and avoiding the scared glances of other cyclist, he managed to stop just in the edge of the red light. Another plus point for foresight. A conquering smile and a puckish raising of eyebrows to the girl next to him made clear how often he biked under these conditions. 

Nevertheless, deadlines, as bornlines, do exists. The traffic light turned amber and he was ready for winning another couple of second to life. In a nutshell, you cannot beat life. With a greater detail, the impulse from the transverse abdominal was sent through the iliotibial tract directly to the soleus. There, thanks to the lever action of the right ankle the force was transported to the end of the thumb metatarsal, just before the join with the proximal phalange. Therefore, all the force was transmitted by the area of contact between the foot and the pedal, which was quite reduced. The rust in the rear dropout impeded the rotation of the cassette and the chain did not stand the pressure exerted by the chain ring. It broke apart. Due to the tension in the knee was unexpectedly released, his anterior cruciate ligament suffered a severe sprain, and the left calf muscle was the responsible for stopping the sharply-edged pedal. The rust was now glued to his muscle fibers. Fortunately, he was vaccinated against tetanus. Another plus point for scientific foresight.

How long does pain take to hit the brain? How long does it take to leave? Pain is an interesting process. Sometimes physiological, sometimes psychological. When less expected Facebook offers another video of a guy breaking clapboard, or a bunch of Hindus slapping each other with fluorescent lamps. Internet is full of answers. 

He held back the tears and stifled a shriek. A whole life of learning for taming our raw condition. Confucius would not have cursed. He did. He got off the bike and sat on the sidewalk. Why was he so idiot? Where was now the smartest guy on town? The playful smiles? The always just five minutes late boy?

He had time again. He would take the best from the fact that he had a genuine excuse to be late. Really late this time. 

Five minutes were gone. The street, the time, did not stop. Why should they? Cars continued passing by, cyclist looked at him surprised and confused, and the forever-changing traffic light kept on going red, amber, green, amber, red. Was life itself like the public transport? Like the traffic circulation? Will not ever stop whatever the event? 

Some birds in the distance took his mind to one of the saddest dawns of his life. The sky was grey; the houses were grey; streets, grey; concrete, grey; sneakers, grey; a couple of empty cartons in his right hand, paperboard color. It started to rain. He looked at the clouds that reminded him “It can always be worse”. The drops in the puddles of rain would not hypnotize him that time. Due to a forgotten reason, he was walking. No rush, no bikes this time. 

He wanted to enjoy the pain of the walk; he did not want to kill himself again, to become numb, like in the past. He would take his time. He would walk. Slowly. He had been disconnected from his emotions for so long that, whatever the occasion, he would savor the bitterest of the feelings.

He thought about her, and obviously, started to cry. Were his eyes the clouds? Were his checks the concrete that less than five minutes ago had supported the weight of a car filled with three people and more than fifteen lives? Together with all the stuff she has collected in an unpredicted year; cartons and boxes of photos, postcards, posters, books, college notes, notebooks, clothes, stationery supplies…; she had taken a huge part of the life of her roommates, her classmates, her friends, of her lover. She was going away with their memories, their experiences, their past, and probably a big part of their present. Damn! It was incredible that no one was doing anything to avoid it. It was incredible that the best thing he had done was hug her for the last time and looked how she started to cry inside the car. He could not have gotten into the car. The stack of boxes and cartons had not left any room available. Even she had had difficulties to get in.

So, she went. She left. The best he could do was staring at the spot where the car had been moving moments ago. 

“I have seen cars leave” he reminded himself to write later. 

Back on the spot where the chain had broken, the tears were running wildly down to his check passing across his jaw. The concrete seemed the same. However, the car was gone. She was gone. The moment was gone. Everything was different. Damn, probably, even the concrete was different. 
“Don’t lie to me fucking inert asphalt! Don’t lie to me!”
Or were the shadow of the clouds what made every situation look different?

## Memories and imagination

It was already too late to go where he had to go, where he wanted to go. Considering the recently made wound in his left calf, and the high chance of getting a severe infection by the rust and dirt of the pedal, visiting a hospital was the best possibility that he could think of. He painfully stood up, took the useless bike, and lock it to the traffic light that had started this new episode of his life. Most likely, the city services would stick a note about the illegality of locking there the bike during the next 48 hours and proceed to its withdrawal in the next week. He better hurry if he didn’t want to lose his main way of commuting. Withdrawal dates, as deadlines, have its type of utility. 

He started walking towards the center of the city, assuming that a big hospital would be more likely to accept a non-emergency like his. 

After a couple hundred meters walking, a bus passed by braking due to a nearby stop. Briefly, pondering the pros and cons of public transport, trying to avoid its negative past-and future- experiences about it, he started jogging, obviously limping. He waved at the bus driver who, after a period of mild depression and the advice of many self-help books, had consciously opted for doing some good deeds to random people throughout the day. The 7 most common ways of suffering, by an author whose named sounded ridiculously funny, had been the one that had convinced him to take control again over his life. It was written in a way where suffering was accepted as the standard condition of human being, something to understand and accept, not to reject and overcome, as so many American ever-improving gurus claimed all the time. 

*Suffering can manifest in a huge variety of ways, many of them can be completely unconscious to ourselves. Simply observe the people in your surroundings, in your day by day life, and try to imagine how easily they would say they are fine or happy with their lives. However, chances are that they are going through an innumerable amount of daily sufferings, as everyone of us does. These people that can happily claim that they wouldn’t change anything in their lives are prone to addiction of many substances and habits. For example, some of the most common addictions nowadays are alcohol, tobacco, or sugar, speaking about substances; and procrastination, social media, and shallow entertainment, when referring to habits.*

*On the other hand, it can be more difficult to find individuals that define themselves as incomplete, as still imperfect, and who take their life with a level of accepted dissatisfaction. Once we understand the implications of guiding our lives under the value of Truth, it will be enlightening to realize the importance of accessing to deeper levels of our beings and minds, to observe ourselves in the way we manifest and analyze the consequences of our actions. Then, we could see with a wider range of emotions those that claim to be peaceful while lighting up cigarettes to calm down their nerves. Where in a near past, such episodes of incoherence caused agitation in our minds with diligent effort and conscious determination, it is possible to transform the agitation into humble compassion.*

The concept more than the words had stuck to the driver’s brain. It was true that he got very annoyed at all those people that were always saying that they were happy when most probably were spending their evenings in the solitude of their rooms watching series. At least him, affected by a lower threshold for loneliness, had realized how negatively the smartphone was affecting his mood and had decided to turn it off once he entered home. More neurologically than magically, he had started sensing that the hours were longer. With the new-found time, he was deeply invested in reversing the downhill direction that his life had taken in the last months and was reading at least one hour in a daily basis. At his 37 years old, he had already assumed that he was completely unskilled for women. However, a book about male models was actually changing that belief and he had the goal of meeting and dating a girl during the next 30 days.

When he saw that guy limping towards the bus and waving his arm like a desperate zombie hungry of compassion, he only could but wait. 

---	Thank you! I really needed to catch the bus. 

-	 No problem. 

-	Is this bus passing close to a hospital?

-	Excuse me?

-	If the bus stops close to a hospital?

-	Hmmm, what happened?

-	My fucking bike broke and I hurt myself with the pedal. 

-	Let me see…

-	It is okay, I think that the people are getting impatient. 

-	Well, it is true. Although that is not our problem, it is theirs. Isn’t it?

That sounded too wise to come from a bus driver that are usually enforced by the rules of the transport company to postpone any type of sincere human interactions for the sake of efficiency. System’s dynamics. 

-	Wow, well, it’s better that I sit, I think. If you remember a hospital that lies nearby any stop, please, let me know. 

-	Done. 

The bus moved again. The mind of the bus driver travelled around his cognitive map, while the hurt guy’s mind prospectively materialized to a moment where buses were driven by machines and he wouldn’t have been able to avoid paying the ticket with the distracting conversation. He imagined a future where devices in our pockets or the back of our hands, under the skin and above the sesamoid bone between the first right proximal phalanx and metacarpal, geolocalise Sapiens with a level of accuracy and connectivity that could withdraw instantly the precise amount of money from the bank account according to the type of public transport that was being used. This simple. It was all our choice.

Submerged in these thoughts that he couldn’t define as pre or post-apocalyptic, the driver verbalized his insight. 

-	There is a hospital close to the next stop, but you have to walk for 15 minutes more or less. Is that okay for you?

In the same way he had answer so many similar questions in his past, he confidently said. 

-	Well, I won’t know until I try. 

Truth as a value. 



